[package]
name = "hexale"
version = "0.1.0"
authors = ["Guillaume Charmetant <cguille.dev@gmail>"]

[dependencies]
iron = "0.6.0"
log = "0.4.0"
simplelog = "0.4.4"
mount = "0.4.0"
staticfile = "0.5.0"
router = "0.6.0"
unicode-normalization = "0.1.5"
uuid = { version = "0.5.1", features = ["v4"] }
